// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AssistantMessage } from "./AssistantMessage";
import type { ToolResultMessage } from "./ToolResultMessage";
import type { UserMessage } from "./UserMessage";

/**
 * Union of all message types visible to the core.
 */
export type AgentMessage = { "role": "user" } & UserMessage | { "role": "assistant" } & AssistantMessage | { "role": "tool_result" } & ToolResultMessage;
