// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentMessage } from "./AgentMessage";
import type { CancelReason } from "./CancelReason";
import type { ContentDelta } from "./ContentDelta";
import type { ToolCallId } from "./ToolCallId";
import type { ToolName } from "./ToolName";
import type { ToolOutputStream } from "./ToolOutputStream";
import type { ToolResult } from "./ToolResult";
import type { ToolResultMessage } from "./ToolResultMessage";

/**
 * Events emitted by the core to notify the host of state changes.
 */
export type AgentEvent =
	| { type: "agent_start" }
	| { type: "agent_end"; messages: Array<AgentMessage> }
	| { type: "turn_start" }
	| {
			type: "turn_end";
			message: AgentMessage;
			tool_results: Array<ToolResultMessage>;
	  }
	| { type: "message_start"; message: AgentMessage }
	| { type: "message_update"; message: AgentMessage; delta: ContentDelta }
	| { type: "message_end"; message: AgentMessage }
	| {
			type: "tool_execution_start";
			tool_call_id: ToolCallId;
			tool_name: ToolName;
			args: object | undefined;
	  }
	| {
			type: "tool_execution_update";
			tool_call_id: ToolCallId;
			stream: ToolOutputStream;
			chunk: string;
			sequence: bigint;
			timestamp: bigint;
	  }
	| {
			type: "tool_execution_end";
			tool_call_id: ToolCallId;
			result: ToolResult;
			is_error: boolean;
	  }
	| {
			type: "tool_execution_cancelled";
			tool_call_id: ToolCallId;
			reason: CancelReason;
	  }
	| {
			type: "queue_update";
			steer: Array<AgentMessage>;
			follow_up: Array<AgentMessage>;
	  }
	| { type: "save_point"; had_pending_writes: boolean }
	| { type: "settled" };
