// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentMessage } from "./AgentMessage";
import type { CancelReason } from "./CancelReason";
import type { LlmContext } from "./LlmContext";
import type { SessionId } from "./SessionId";
import type { ToolCall } from "./ToolCall";
import type { ToolCallId } from "./ToolCallId";
import type { WaitMode } from "./WaitMode";

/**
 * Actions that the core requests the host to perform.
 */
export type AgentAction = { "type": "stream_llm", context: LlmContext, session_id: SessionId | null, } | { "type": "execute_tools", calls: Array<ToolCall>, } | { "type": "cancel_tools", tool_call_ids: Array<ToolCallId>, reason: CancelReason, } | { "type": "wait_for_input", mode: WaitMode, } | { "type": "finished", messages: Array<AgentMessage>, };
