// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentMessage } from "./AgentMessage";
import type { Model } from "./Model";
import type { ThinkingLevel } from "./ThinkingLevel";
import type { ToolDefinition } from "./ToolDefinition";

/**
 * Public agent state.
 */
export type AgentState = {
	system_prompt: string;
	model: Model;
	thinking_level: ThinkingLevel;
	tools: Array<ToolDefinition>;
	messages: Array<AgentMessage>;
	is_streaming: boolean;
	streaming_message: AgentMessage | null;
	pending_tool_calls: Array<string>;
	error_message: string | null;
};
