// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ApiName } from "./ApiName";
import type { ModelCapabilities } from "./ModelCapabilities";
import type { ModelCost } from "./ModelCost";
import type { ModelId } from "./ModelId";
import type { ModelName } from "./ModelName";
import type { ProviderName } from "./ProviderName";

/**
 * Describes a concrete LLM model and its provider.
 */
export type Model = {
	id: ModelId;
	name: ModelName;
	api: ApiName;
	provider: ProviderName;
	base_url: string | null;
	reasoning: boolean;
	context_window: number;
	max_tokens: number;
	capabilities: ModelCapabilities;
	cost: ModelCost;
};
