// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExecutionMode } from "./ExecutionMode";
import type { ToolName } from "./ToolName";

/**
 * Metadata describing a tool available to the agent.
 * Hosts implement the actual execution; core only holds the schema.
 */
export type ToolDefinition = { name: ToolName, label: string, description: string, parameters: object, execution_mode: ExecutionMode, };
